<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="PRG_Mainprg" Id="{46dc0a52-037b-448e-a078-a6fc86bf45d8}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM PRG_Mainprg
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[PRG_Conveyor01();
PRG_Conveyor02();
PRG_ExitConvetor();
PRG_Load01();
PRG_Load02();
PRG_TransferLeft01();
PRG_TransferLeft02();

PRG_AtEntry01();
PRG_AtEntry02();
PRG_AtExit01();
PRG_AtTransfer01();
PRG_AtTransfer02();]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>