<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="MAIN" Id="{1fc035af-53d0-4100-abf7-dbd437ade9fb}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[PRG_Mainprg();
PRG_CONTROLM1();

FIO_Read_Inputs();
FIO_Write_Outputs();
ReadWriteIO();
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>